language: python
python:
  - 3.6
deploy:
  provider: pypi
  user: andreroggeri
  password:
    secure: OkoZNPz0N3Mn4loPH+PmqAVTAcXsfieUEk20sjZwK1Nz/MrZqciflzDo9ck+DLv5hkvVoFDLFE491ETpKZb7h0MbtNqW5bNiijMP8frBndcLegSlzYrdtEE8L0SmWuIXruS+xCEZFQCmwj7ERin10cEP0/VaXg6CLrMkhUhxYKh+vRBdaFVU4IhwYoPE6li+eRb1/5T/izyfl8Rs6uMo0U/SahN4ISZePwPQmRlhkRGpyMT/iHAHpDwfLI3n6rNRw/7YmgBw6Om5JgCL+YSkzCKG6p/7afs+nSC70TlTAZTZCVvEe2YHm2Bz4gi9gLFHxW6Y4BeTqUrv3kKiipGBazQ5LBdCUp89WjT4Bz6ShQrP3A+kWRrX9SUjQgHL63JgnOafE/IJSuAA6Pe7ylkuubWXwYI1o9i9OCN5FRZDpt294Cp17uCYYFQOwqHdV048plyVyESjKQZaJRpqrF+yylIVp7guhCsk0BNFUKC1q14QFkjlLSaEL/9F5bUxt/g2QturhMAAXr0yIqo5cGRhREyhJn97UvtwFrcYAqUFltcfzQP6usyAQUucuxXdd26T32FT7P558EBdVgvyLGhNB/y8Hc1z9vcR1ebfsqyctig+7nJldkb8tRtIcYdgOHb5Z+iCpOI4TlCDo2dNMaYCGqCO7U+rXUPpZhNmSAp5SKw=