language: python
python:
- '3.6'
script: python --version
deploy:
  provider: pypi
  user: andreroggeri
  password:
    secure: rV6vCur89PWkSkaz6/q5PrSMqthiol74yDRuw+FJekelQtVqNEKWp8sTCuwbmSad+dzalvtKyTY3QV0oU2yiUMjRwpbDUqPCT2oZ7I50+clencB4rwmcUpI8c9I+18yBTK25KRDJb8bKRA9SfGHOHzPxiuHNjJklfo6ic2X++H4Cv4vfNBAyuJOHbaER2caPaIk06wsxFZBixDrTS3KJx0aSqBS3x5gONrLVOxzXDvpf0lQqKjlo8CXTp+22os/YPchIeFDVIqqkPAU4duh7Hfg6u0IVLlShlD8WxiPN+QC5yat2b5lWUOvrJtRC40L+fvao4APKzCmza0GQRj1keHk439Zpbl62ce+o3AayowvGQEk9SQELlSQJfRTBaRsJFspKs1Z2pvMAVj490x+yQVyZ7ylqEwjTQWxSJHMk+B8VYuE/sM6F6PEzOBoTc0SYhITIi2KvMZMZeesrYACsyppjpOzooZ69sgX+ynPEhhdktrUg7ugJ+dtnlnsetuH8cf2190KlKSOzc1EYVkJYcBAYXh4cGU1AWX9vWJlykr8CNTocwLp5icCTJYupT1z96KCOUui/QYdjie9z715rHWLan2rrlhsBeCY6oEq5Vl5z9CkW/u64TiL62MAvz2tSZjrjSK/yXw244pb3+Yi43XkhmXoEdbcPm59Sfdm3PX8=
  on:
    tags: true
